### ISSUE TITLE
2019.3.11-3.17 TODO list

### ISSUE THREAD

**Issue by Mike-Dai** [Mike-Dai/djangocoder#26]
- [x] Split widget title and content in sidebar.

- [x] Cancel the margin between top post and navbar in search page and draft page.

- [x] Add a foot for site.

- [x] Move logout into user dropdown.

- [x] Change search button into icon.

- [x] Make the profile page editable.

- [x] Beautify the write blog form.

- [ ] Move comment form to post detail page. It should be showed below the post. We should not redirect visitor to another page.

- [x] Add a breadcrumb below the navbar.

- [x] Add a title for comment list.

- [ ] Enable the tags selection in post new form and post edit form.

- [x] When search return no result, the message should be showed in a container.

- [x] Remove the shadow of sidebar.
- [ ] Set background color for footer.
- [ ] Change the color of buttons. We should use a darker color, which matches the blog theme better.
- [ ] When content is short, the footer is showed just below the content. It should stick to the bottom of site.
- [ ] Change the font.
- [ ] Remove buttons below post in detail page. Add small icon at right-top corner.
